<h1>
student id: 8920299 <br>
name: Aashi Aggarwal
</h1>


<h3>
Using Tensorflow:<br>
Calculate the dot product between the same vectors as above (re-define them in Tensorflow)
</h3>

In [6]:
import tensorflow as t
vector1 = t.constant([9,8,3])
vector2 = t.constant([8,50,16])

print(vector1)
print(vector2)

print(t.tensordot(vector1,vector2,axes=1))

tf.Tensor([9 8 3], shape=(3,), dtype=int32)
tf.Tensor([ 8 50 16], shape=(3,), dtype=int32)
tf.Tensor(520, shape=(), dtype=int32)


<h3>
Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)
</h3>

In [7]:
matrix1 = t.constant([[22,2],[3,66]])
matrix2 = t.constant([[5,32],[14,8]])

print(t.matmul(matrix1,matrix2))


tf.Tensor(
[[138 720]
 [939 624]], shape=(2, 2), dtype=int32)
